# Generated by Django 4.0.4 on 2023-04-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_comment_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
