# Generated by Django 4.0.4 on 2023-04-10 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlisting_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='startingBid',
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='comment',
            name='auction',
            field=models.ManyToManyField(related_name='comments', to='auctions.auctionlisting'),
        ),
    ]
