# Generated by Django 4.0.4 on 2023-04-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist_auctions_alter_watchlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auctions',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auctions',
            field=models.ManyToManyField(null=True, to='auctions.auctionlisting'),
        ),
    ]
