# Generated by Django 4.0.4 on 2023-04-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_watchlist_auctions_watchlist_auctions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auctions',
            field=models.ManyToManyField(to='auctions.auctionlisting'),
        ),
    ]
